// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUMqYSPUXXZ6uuwfLv9R5ySGyuEGH-S2Y',
    appId: '1:103839979737:web:4fb6fa96fb96ae35e646c8',
    messagingSenderId: '103839979737',
    projectId: 'gnb-task-flutter',
    authDomain: 'gnb-task-flutter.firebaseapp.com',
    storageBucket: 'gnb-task-flutter.firebasestorage.app',
    measurementId: 'G-RPBTC2C0QQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-7LSCpikjpbXH2Y3V2mfriP3FoWkxuYs',
    appId: '1:103839979737:android:dfc605eb76043f8fe646c8',
    messagingSenderId: '103839979737',
    projectId: 'gnb-task-flutter',
    storageBucket: 'gnb-task-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUOV9Tag3lInCsOdrK1OezoEBbo_lY_QM',
    appId: '1:103839979737:ios:51e0a2fb1be9a125e646c8',
    messagingSenderId: '103839979737',
    projectId: 'gnb-task-flutter',
    storageBucket: 'gnb-task-flutter.firebasestorage.app',
    iosBundleId: 'com.example.gnbFlutterTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUOV9Tag3lInCsOdrK1OezoEBbo_lY_QM',
    appId: '1:103839979737:ios:51e0a2fb1be9a125e646c8',
    messagingSenderId: '103839979737',
    projectId: 'gnb-task-flutter',
    storageBucket: 'gnb-task-flutter.firebasestorage.app',
    iosBundleId: 'com.example.gnbFlutterTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUMqYSPUXXZ6uuwfLv9R5ySGyuEGH-S2Y',
    appId: '1:103839979737:web:a4df2cc99fbd358de646c8',
    messagingSenderId: '103839979737',
    projectId: 'gnb-task-flutter',
    authDomain: 'gnb-task-flutter.firebaseapp.com',
    storageBucket: 'gnb-task-flutter.firebasestorage.app',
    measurementId: 'G-GDSPNR70B9',
  );
}
